
### Signup
POST http://localhost:5000/signup
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "yourpassword"
}

### Login
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "yourpassword"
}

### Logout
POST http://localhost:5000/logout
Content-Type: application/json
